services:
  mysql:
    image: mysql:8.0
    container_name: nextlevel-mysql
    restart: unless-stopped
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: nextlevel
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./nextlevel.sql:/docker-entrypoint-initdb.d/nextlevel.sql:ro
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - nextlevel-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: nextlevel-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=
      - DB_NAME=nextlevel
      - DB_PORT=3306
    depends_on:
      - mysql
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - nextlevel-network

volumes:
  mysql_data:

networks:
  nextlevel-network:
    driver: bridge
